import { DemoLedger, euros } from './ledger.mjs';
const $=s=>document.querySelector(s), ledger=new DemoLedger({now:()=>new Date().toISOString()});
let surEnabled=false,timer=null,refundBusy=false,lastRefund=null,refundTimer=null;
const openSim=()=>{const n=$('#localSimulation'); if(n) n.open=true};
const say=t=>$('#live').textContent=t, cents=v=>/^-?\d+(?:[.,]\d{1,2})?$/.test(String(v).trim())?Math.round(Number(String(v).replace(',','.'))*100):NaN, data=()=>({amountCents:cents($('#amount').value),feePercent:Number($('#fee').value),stripeCostCents:175});
function invalid(){const {amountCents,feePercent}=data();return !Number.isSafeInteger(amountCents)||amountCents<=0?'Introduce un importe mayor que 0,00 €.':$('#fee').value.trim()===''||!Number.isFinite(feePercent)||feePercent<0||feePercent>100?'La comisión debe estar entre 0 y 100%.':''}
function formError(t=''){ $('#formError').hidden=!t;$('#formError').textContent=t }
function payload(){const {amountCents,feePercent}=data(),fee=Math.round(amountCents*feePercent/100);return {mode:'payment',line_items:[{price_data:{currency:'eur',product_data:{name:'Servicio de partner (demo)'},unit_amount:amountCents},quantity:1}],payment_intent_data:{transfer_data:{destination:$('#partner').value==='norte'?'acct_demo_norte':'acct_demo_sur'},application_fee_amount:fee,metadata:{partner_id:$('#partner').value,simulated:'true'}},metadata:{simulation_id:'demo_checkout_preview'}}}
function inspector(){$('#payload').textContent=JSON.stringify(payload(),null,2)}
function preview(){const e=invalid();formError(e);if(e||ledger.payment)return;const {amountCents,feePercent,stripeCostCents}=data(),fee=Math.round(amountCents*feePercent/100);$('#total').textContent=euros(amountCents);$('#platform').textContent=euros(fee-stripeCostCents);$('#partnerBalance').textContent=euros(amountCents-fee);$('#commission').textContent=`Comisión ${euros(fee)} − coste ${euros(stripeCostCents)}`;inspector()}
function lock(v){['#partner','#amount','#fee'].forEach(x=>$(x).disabled=v);$('#simulate').disabled=v;$('#reject').disabled=v}
function render(){const p=ledger.payment, paid=p?.status==='succeeded';lock(!!p);if(paid||p?.status==='rejected'){['#totalLabel','#platformLabel','#partnerLabel'].forEach((x,i)=>$(x).textContent=['Cliente','Plataforma','Partner'][i]+' · resultado de la simulación');$('#total').textContent=euros(ledger.balances.customer);$('#platform').textContent=euros(ledger.balances.platform);$('#partnerBalance').textContent=euros(ledger.balances.partnerPending);$('#commission').textContent=`Coste procesado: ${euros(ledger.balances.feesProcessed)}`;$('#balanceNote').textContent='Saldos del registro simulado'}else{['#totalLabel','#platformLabel','#partnerLabel'].forEach((x,i)=>$(x).textContent=['Cliente','Plataforma','Partner'][i]+' · vista previa');$('#balanceNote').textContent='Saldo pendiente · no cuenta bancaria';if(!p)preview()}$('#paymentState').textContent=!p?'Aún no hay transacción activa.':p.status==='pending'?`Cobro ${p.id}: pendiente de evento simulado.`:p.status==='rejected'?`Cobro ${p.id}: rechazado. No se movieron saldos.`:`Cobro ${p.id}: aprobado. Reembolsado: ${euros(p.refundedCents)}.`;$('#events').innerHTML=ledger.events.slice().reverse().map(e=>`<li><strong>${e.id} · ${e.type}</strong><span>${new Date(e.at).toLocaleString('es-ES')}</span></li>`).join('')||'<li><span>El registro aparecerá al simular un cobro.</span></li>';$('#refund').disabled=!paid||refundBusy;$('#refundAll').disabled=!paid||refundBusy||p.refundedCents===p.amountCents;$('#refundRepeat').disabled=!lastRefund||refundBusy;inspector()}
function simulate(outcome='approved'){openSim();if(ledger.payment||timer)return;const e=invalid();if(e){formError(e);return say(e)}const blocked=$('#partner').value==='sur'&&!surEnabled;$('#blocker').hidden=!blocked;if(blocked){$('#blocker').textContent='Sur necesita completar su alta simulada en Partners antes de cobrar.';return say('Cobro bloqueado: alta de partner pendiente.')}try{const p=ledger.createPayment({partnerId:$('#partner').value,...data()});render();say('Cobro pendiente creado.');const id=p.id;timer=setTimeout(()=>{timer=null;if(ledger.payment?.id!==id||ledger.payment.status!=='pending')return;ledger.settle({outcome});render();say(outcome==='approved'?'Cobro aprobado y registro actualizado.':'Cobro rechazado sin movimiento de saldos.')},450)}catch(e){$('#blocker').hidden=false;$('#blocker').textContent=e.message;say(e.message)}}
function refund(amount,key){openSim();if(refundBusy)return;refundBusy=true;render();try{const r=ledger.refund(amount,key);if(!r.duplicate)lastRefund={amount,key};say(r.duplicate?'Reembolso repetido: el saldo no cambió.':'Reembolso aplicado.')}catch(e){say(e.message)}finally{render();refundTimer=setTimeout(()=>{refundTimer=null;refundBusy=false;render()},300)}}
document.querySelectorAll('[role=tab]').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('[role=tab]').forEach(t=>{const a=t===tab;t.setAttribute('aria-selected',a);t.tabIndex=a?0:-1;$(`#${t.getAttribute('aria-controls')}`).hidden=!a});tab.focus()}));
['#amount','#fee','#partner'].forEach(x=>$(x).addEventListener('input',preview));$('#simulate').onclick=()=>simulate();$('#reject').onclick=()=>simulate('rejected');$('#repeat').onclick=()=>{openSim();try{const r=ledger.settle();render();say(r.duplicate?'Webhook repetido: ignorado; no se duplicó saldo.':'Evento aplicado.')}catch(e){say(e.message)}};
$('#refund').onclick=()=>{const a=cents($('#refundAmount').value);if(!Number.isSafeInteger(a)||a<=0)return say('Introduce un importe de reembolso válido.');refund(a,`refund:${ledger.payment.id}:${ledger.payment.refundedCents}:${a}`)};$('#refundAll').onclick=()=>{const p=ledger.payment,a=p.amountCents-p.refundedCents;refund(a,`refund:${p.id}:${p.refundedCents}:${a}`)};$('#refundRepeat').onclick=()=>refund(lastRefund.amount,lastRefund.key);
$('#reset').onclick=()=>{openSim();if(timer)clearTimeout(timer);if(refundTimer)clearTimeout(refundTimer);refundTimer=null;timer=null;ledger.reset();lastRefund=null;refundBusy=false;surEnabled=false;$('#surState').textContent='Alta pendiente';$('#surState').className='';$('#onboard').disabled=false;$('#onboard').textContent='Completar alta simulada';$('#blocker').hidden=true;formError();render();say('Demo reiniciada: Sur y todos los saldos se restauraron.')};$('#onboard').onclick=()=>{surEnabled=true;$('#surState').textContent='Habilitado';$('#surState').className='ok';$('#onboard').disabled=true;$('#onboard').textContent='Alta completada';say('Alta de Sur completada en esta simulación.')};
$('#copyPayload').onclick=async()=>{try{await navigator.clipboard.writeText(JSON.stringify(payload(),null,2));say('Payload copiado.')}catch{say('No se pudo copiar; selecciona el payload manualmente.')}};$('#download').onclick=()=>{const b=new Blob([JSON.stringify(ledger.evidence(),null,2)],{type:'application/json'}),a=Object.assign(document.createElement('a'),{href:URL.createObjectURL(b),download:'demo-evidencia.json'});a.click();URL.revokeObjectURL(a.href);say('Evidencia JSON descargada.')};$('#contact').onclick=async()=>{const message='Hola Roberto, he visto la demo de pagos para partners. Me gustaría revisar contigo el diseño del SaaS, el alcance y los hitos para lanzarlo.';try{await navigator.clipboard.writeText(message);say('Mensaje copiado. Puedes pegarlo en nuestra conversación de LinkedIn.')}catch{say(message)}};preview();render();

document.querySelector('.tabs').addEventListener('keydown', e => {
  if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(e.key)) return;
  e.preventDefault();
  const tabs = [...document.querySelectorAll('[role=tab]')];
  const current = tabs.indexOf(document.activeElement);
  const next = e.key === 'Home' ? 0 : e.key === 'End' ? tabs.length - 1 : (current + (e.key === 'ArrowRight' ? 1 : -1) + tabs.length) % tabs.length;
  tabs[next].click();
});
